const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const CREATE_STREAM = 'CREATE_STREAM';
const FETCH_STREAMS = 'FETCH_STREAMS';
const FETCH_STREAM = 'FETCH_STREAM';
const UPDATE_STREAM = 'UPDATE_STREAM';
const DELETE_STREAM = 'DELETE_STREAM';

export { 
    SIGN_IN, 
    SIGN_OUT, 
    CREATE_STREAM, 
    FETCH_STREAMS, 
    FETCH_STREAM,
    UPDATE_STREAM,
    DELETE_STREAM
};